In [2]:
#Martix Arithmetic

In [3]:
import numpy as np

In [4]:
a = np.array([1, 4, 5])

In [5]:
b = np.array([-1, 4, 53])

In [6]:
c = a + b

In [7]:
d = a * b

In [8]:
c

array([ 0,  8, 58])

In [9]:
d

array([ -1,  16, 265])

In [10]:
m1 = np.array([[1, 4], [-5, 8]])

In [11]:
m2 = ([[7, -6], [-11, 2]])

In [12]:
msum = m1 + m2

In [13]:
product = np.dot(m1, m2)

In [14]:
msum

array([[  8,  -2],
       [-16,  10]])

In [15]:
product

array([[ -37,    2],
       [-123,   46]])

In [16]:
#Null martix

In [17]:
zeros = np.zeros((2,3))

In [18]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
#Identity martix

In [20]:
i = np.identity(3)

In [21]:
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])